spring.thymeleaf.prefix: classpath:/template/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.cache: true

security.basic.enabled: false

server:
    port: 80

# OpenIoT 配置
bupt.thingsboard:
  #host: 10.108.216.193 # for cc
  #host: 10.108.217.227 # for gpu
  #host: 127.0.0.1
  host: 39.104.84.131
  port: 8080


device-access:
 host:
 port:

smart_ruler:
  host:
  port:

service-management:
  host:
  port:

account:
  host: 10.112.233.200
  port: 8081
#  url需修改
  login_url: http://${account.host}:${account.port}/oauth/token
  logout_url: http://${account.host}:${account.port}/logout
  client_id: client_2
  client_secret: 123456