spring.thymeleaf.prefix: classpath:/template/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.cache: true

security.basic.enabled: false

server:
    port: 80

# OpenIoT 配置
bupt.thingsboard:
  #host: 10.108.216.193 # for cc
  #host: 10.108.217.227 # for gpu
  #host: 127.0.0.1
  host: 39.104.84.131
  port: 8080


device-access:
 host: 10.108.218.108
 port: 8100

smart_ruler:
  host: 10.108.218.108
  port: 8200

service-management:
  host: 10.108.218.108
  port: 8000

account:
  host: 10.112.233.200
  port: 8081
  login_url: http://${account.host}:${account.port}/api/v1/auth/login
  logout_url: http://${account.host}:${account.port}/api/v1/auth/logout
  client_id: client_2
  client_secret: 123456